### ISSUE TITLE
lookup_* for empty (or sometimes too small) time range results in redis error

### ISSUE THREAD

**Issue by meastman** [educreations/activity-tracker#3]
```python
tracker.lookup_monthly(
    start=datetime.date(2014, 2, 2),
    end=datetime.date(2014, 2, 6))
```

results in the following exception:
`wrong number of arguments for 'mget' command`

since we call `mget` for each bucket with the empty set of keys

**Comment by meastman** [comment]
This is probably as simple as wrapping the final izip/conn.mget in `backends.redis.RedisBackend.lookup` in `if keys:` or adding an early return. When there are no keys, there are no full time periods, so the method should just return `{}`.

**Comment by frewsxcv** [comment]
> so the method should just return {}.

You mean `[]`, right?

**Comment by meastman** [comment]
> You mean `[]`, right?

Sorry, no, I misremembered how the code works. For the specific case in the first comment, it should be `[]` because there are no full months. For the test case in PR #5, It should also return `[]` because `start` and `end` are in reverse chronological order (so there are no full months after `start` and before `end`. Generally, it should return a list of (date, dict) tuples, where each dict is `{$bucket1: 0, $bucket2: 0, ...}`.

**Comment by meastman** [comment]
It looks like we only attempt to lookup the empty set of keys when there are no complete time periods, in which case we should return `[]`, so yes.
